{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oci2gdsd-daemon.serviceAccountName" . }}
  labels:
{{ include "oci2gdsd-daemon.labels" . | indent 4 }}
{{- end }}
