FROM golang:1.23.6-bookworm AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/oci2gdsd ./cmd/oci2gdsd

FROM alpine:3.21

RUN apk add --no-cache ca-certificates bash
COPY --from=build /out/oci2gdsd /usr/local/bin/oci2gdsd
ENTRYPOINT ["/usr/local/bin/oci2gdsd"]
